### ISSUE TITLE
Cant add an attachment

### ISSUE THREAD

**Issue by cerullo** [DNNCommunity/DNN.Newsletter#10] opened 2019-04-17 18:47 UTC
## Software Versions
- DNN: 9.2.2
- Module: 08.00.00

## To Reproduce
1. Go to Manage Menu
2. Click on Newsletters
3. create an email and add an attachment. 
4. Send the email
5. You are emailed a failed bulk email report and there is an error in the admin logs

## Expected behavior
send the email and attachment

## Error log
AbsoluteURL:
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:5aaa8b1d-3fc0-40ec-a0b2-163ac04d75d3
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:zowhwx3DDPzxkQZHEKOvWWUHka0=
Message:Cannot access a closed Stream.
StackTrace:
at System.IO.__Error.StreamIsClosed()
at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
at System.Net.Mime.MimePart.Send(BaseWriter writer, Boolean allowUnicode)
at System.Net.Mime.MimeMultiPart.Send(BaseWriter writer, Boolean allowUnicode)
at System.Net.Mime.MimeMultiPart.Send(BaseWriter writer, Boolean allowUnicode)
at System.Net.Mail.SmtpClient.Send(MailMessage message)
InnerMessage:
InnerStackTrace:
Source:mscorlib
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: XXX

**Comment by david-poindexter** [comment] 2019-09-20 21:43
@cerullo I can confirm this behavior on DNN 09.01.01 as well.  The file gets attached and sent, but seems to be corrupted when recipients attempt to open.  I am getting ready to see if I can get this project to build locally.

**Comment by david-poindexter** [comment] 2019-09-21 20:25
@cerullo are you experiencing this with both Synchronous and Asynchronous?

**Comment by cerullo** [comment] 2019-09-22 00:21
Yes I am



Thanks,
Renee

 Integrated web design, digital marketing and technology solutions for the busy entrepreneur.
-----
Renee Cerullo
RLComputing is WBE Certified
President, RLComputing<http://www.rlcomputing.com/>
HELP DESK - support.RLComputing.com<http://support.rlcomputing.com/>
Phone: 716.656.8958
Fax: 1.866.375.3393
Skype: renee.cerullo
Hours of Operation: Monday thru Friday 8am - 5pm EST

**Comment by david-poindexter** [comment] 2019-09-22 00:28
Thanks for the confirmation.  That's what I am seeing as well (though the behavior for each is slightly different - messages, etc.).  I am trying now to determine if this is an issue with this module or the underlying DNN API.  I'll keep you posted on progress.

**Comment by david-poindexter** [comment] 2019-09-27 22:29
QUICK UPDATE: It appears the issue may be in the DNN Platform API.  I am working to prove or disprove this now.

**Comment by david-poindexter** [comment] 2019-09-28 06:17
Okay, we have isolated the issue and it is in fact an issue in the DNN API.  Thanks to @valadas @donker and @EPTamminga for the great collaboration on this.

Here are the plans:

1. A DNN Platfrom issue has been created at dnnsoftware/DNN.Platform#3036 and I will be creating a pull request to resolve this.  
 
2. I will release DNN.Newsletter 08.00.01 to provide a workaround for anyone that cannot wait for or upgrade to DNN 09.04.02.
 
3. I will release DNN.Newsletter 08.01.00 to support DNN 09.04.02+.

**Comment by cerullo** [comment] 2019-09-28 11:05
Awesome thank you so much!!


Thanks,
Renee

 Integrated web design, digital marketing and technology solutions for the busy entrepreneur.
-----
Renee Cerullo
RLComputing is WBE Certified
President, RLComputing<http://www.rlcomputing.com/>
HELP DESK - support.RLComputing.com<http://support.rlcomputing.com/>
Phone: 716.656.8958
Fax: 1.866.375.3393

**Comment by david-poindexter** [comment] 2019-09-30 00:03
A pull request has now been submitted to DNN Platform - https://github.com/dnnsoftware/Dnn.Platform/pull/3039

**Comment by david-poindexter** [comment] 2019-10-10 14:57
Okay, great news - the pull request (https://github.com/dnnsoftware/Dnn.Platform/pull/3039) has now been approved and merged.  This will fix things for DNN 09.04.02.  We will start work on the 08.00.01 release of this module now.

**Comment by david-poindexter** [comment] 2019-10-14 21:15
Closing per #19 - the fix will be included in the upcoming **08.00.01** release.

**Closed as completed by david-poindexter** 2019-10-14 21:15 UTC
Labels: bug

**Comment by david-poindexter** [comment] 2019-10-14 23:33
@cerullo we just released version **08.00.01** - see https://github.com/DNNCommunity/DNN.Newsletter/releases/tag/v8.0.1

**Comment by cerullo** [comment] 2019-10-14 23:57
This group is so amazing! Thanks for the quick turnaround. Will start updating my clients!



Thanks,
Renee

 Integrated web design, digital marketing and technology solutions for the busy entrepreneur.
-----
Renee Cerullo
RLComputing is WBE Certified
President, RLComputing<http://www.rlcomputing.com/>
HELP DESK - support.RLComputing.com<http://support.rlcomputing.com/>
Phone: 716.656.8958
Fax: 1.866.375.3393
Skype: renee.cerullo
Hours of Operation: Monday thru Friday 8am - 5pm EST
